(function(){
	angular.module("app").config(route);
	function route($routeProvider){
		$routeProvider
		.when("/signUp",{
			templateUrl:"app/views/signUp.html"
		})
		.when("/artists",{
			templateUrl:"app/views/artists.html"
		})
		.when("/clientView",{
			templateUrl:"app/views/clientView.html",
			controller:"clientView"
		})
		.when("/login",{
			templateUrl:"app/views/login.html"
		})
		.when("/home",{
			templateUrl:"app/views/home.html",
			controller:"home"
		})
		.otherwise("/login");
	}
})();
